# Project: Sweep
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o Functions.o
LINKOBJ  = main.o Functions.o
LIBS     = -L"C:/Users/S100/Desktop/DevCppPortable/MinGW64/lib" -L"C:/Users/S100/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/S100/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/S100/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/S100/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/S100/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/S100/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/S100/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/S100/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Sweep.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Functions.o: Functions.cpp
	$(CPP) -c Functions.cpp -o Functions.o $(CXXFLAGS)
